### ISSUE TITLE
Incorporating lightbox feature including within a margin note

### ISSUE THREAD

**Issue by howardm** [nstrayer/tuftesque#20]
Hi,

Here is a lightbox function that works nicely in Distill: https://github.com/rstudio/distill/issues/105

Can one incorporate this into a margin note in Tuftesque ? That is, within the tufte::margin_note directive ?

If so, how ?

Thanks.

Howard

**Comment by nstrayer** [comment]
That looks very promising! I will test it out later today to see if it works as a drop in.

**Comment by nstrayer** [comment]
Hi @howardm, 

Based on the code from the sent example I put together a temporary solution for lightboxed images in margin-notes for tuftesque pages. 

This is the result of the following code: 
![image](https://user-images.githubusercontent.com/6764693/67423105-43ee4180-f599-11e9-8e2f-c8542da8c6a4.png)


It involves three code blocks. First in an R code chunk somewhere before the first margin-note with a lightbox, put: 
```r
lightboxed_margin <- function(content){
  wrapped_content <- paste("<span class = 'lightbox'>", content, "</span>")
  tufte::margin_note(wrapped_content)
}
```

Then wherever you desire in your page place the following javascript: 


````
```{js}
const selected_class = 'lightbox-loaded';
window.addEventListener('load', function() {
  // Select all the windowboxable images
  const lightboxed_elements = document.querySelectorAll('.lightbox img');
  lightboxed_elements.forEach(function(element) {
    element.addEventListener('click', function(){
      const is_selected = this.classList.contains(selected_class);
      if(is_selected){
        this.classList.remove(selected_class);
      } else {
        this.classList.add(selected_class);
      }
    });
  });
});
```
````

and finally the following css chunk

````
```{css}
/* Style activated by the addition of the selected class */
.lightbox-loaded {
  position: fixed;
  z-index: 999;
  width: 90%;
  height: auto;
  max-height: 90%;
  left: 50%;
  top: 50%;
  transform: translate(-50%, -50%);
  box-shadow: 0px 0px 50px black;
}
````

The original code from the distill thread won't work because tuftesque margin-notes are spans and not divs and also we don't have jquery loaded.

**Comment by nstrayer** [comment]
I updated the code here on github for tuftesque to have lightbox support built-in. I have yet to release it on the master branch but you can update to the new [lightboxes branch](https://github.com/nstrayer/tuftesque/tree/lightboxes) with 
`blogdown::install_theme('nstrayer/tuftesque@lightboxes', force = TRUE)`

I have tested it on livefreeordichotomize and it works well. You'll still need to include the `lightboxed_margin()` function at the top of the page but all else should just magically work. 

Let me know if it works for you!

**Comment by howardm** [comment]
Great! I'll try it.

Please bear with me...

I  inserted the following at the beginning of the .Rmd file (after the header):
__

`r lightboxed_margin <- function(content){
  wrapped_content <- paste("<span class = 'lightbox'>", content, "</span>")
  tufte::margin_note(wrapped_content)
}`
___
(The start and end backticks are there above)

And then, what's the proper syntax for adding an image in the margin to achieve the lightbox effect ?

I typically use (as an example):   `r tufte::margin_note("![](/images/CXR.jpg)")`

Howard

**Comment by nstrayer** [comment]
Just replace `margin_note` with `lightboxed_margin` for the side notes you want to have as lightboxes.

**Comment by howardm** [comment]
Hi,

When I do so, I get the following:

___
Quitting from lines 2-39 (2019-09-20-testing-this-new-website-with-a-tufte-theme.Rmd) 
Error: 'lightboxed_margin' is not an exported object from 'namespace:tufte'
Execution halted
___

I did update Tuftesque yesterday as you indicated.

Howard

**Comment by nstrayer** [comment]
Oh sorry, I meant replace: `tufte::margin_note` with just `lighboxed_margin`.

**Comment by howardm** [comment]
O.K.

I now have:
__
`r lightboxed_margin("![](/images/CXR.jpg)")`
___
(The backticks are there.)

An image is in the margin, but no lightbox function on clicking the image.

(No error message.)

Howard

**Comment by nstrayer** [comment]
Hmm, 

Did you make sure that the new tuftesque was used? Check to make sure that `themes/tuftesque/static/js/lightbox.js` exists.

**Comment by howardm** [comment]
Hi,

Yes, the lightbox.js is there.

I've noticed additional things:

1. When I add the code directly to the .Rmd page, the lightbox does work. (The code shows up in the web page, though):
___
![Screen Shot 2019-10-24 at 7 36 36 PM](https://user-images.githubusercontent.com/6101226/67536989-cf013180-f696-11e9-85ba-86a63d00e0ad.jpg)
___

2. The image in the lightbox is distorted. The pixel dimensions of this particular image are 1048 X 994. 

![Screen Shot 2019-10-24 at 7 37 28 PM](https://user-images.githubusercontent.com/6101226/67537053-0839a180-f697-11e9-99f5-ff3323382841.jpg)

____

Thanks for your interest!

We're making some progress.

Howard

**Comment by nstrayer** [comment]
Ah, fun stuff. 

As for the code showing up: just add `echo = FALSE` to the chunk declaration:

````
```{js, echo = FALSE}
...
```
````

Not sure why it needs the code manually placed though... I would suggest maybe completely removing the `tuftesque` folder from `themes/` and reinstalling it. 

The aspect ratio thing is interesting, I didn't notice it in my images but it definitely is happening for yours. Try adding this css chunk in your post somewhere and let me know if it fixes it. 

````
```{css, echo = FALSE}
.lightboxed-loaded {
  object-fit: cover;
}
```
````

**Comment by howardm** [comment]
O.K.

I added the additional css chunk in the post, but it still looks like this:

![Screen Shot 2019-10-25 at 3 32 07 PM](https://user-images.githubusercontent.com/6101226/67605859-d9760680-f73c-11e9-872e-19189db80b88.jpg)
____

Howard

**Comment by nstrayer** [comment]
hmm...

Want to post a copy of that image file itself? I'll put it into a local post and see what's going wrong with displaying it.

**Comment by howardm** [comment]
Sure.

Here it is:  https://www.dropbox.com/s/r2hhhwf4v8d8rsn/CXR.jpg?dl=0

Howard

**Comment by nstrayer** [comment]
@howardm , 

Okay I think I got it! 

Two issues with before: 

1. Somehow I never actually put the lightbox css into the master branch of tuftesque. Now you shouldn't need to add a new css chunk into each post. 
2. I fixed the aspect ratio issue (at least with the photo you sent). Before I had the problem because I explicitly told the photo to be 90% of the page width wide, and then said don't let the height get above 95%, this meant that photos that were taller than the windows aspect ratio would be forced to be stretched. Now I only tell it to not get taller than the screen and then set the width to auto meaning it shouldn't ever get wider than the screen. 

Just make sure to update to the latest version of tuftesque now and you _should_ be good. 
Here's what an example I did with your image looks like now. 

![image](https://user-images.githubusercontent.com/6764693/67784136-4b9a6400-fa39-11e9-957f-e749ba2a3a74.png)

Here's the code I used to embed that. 

````
---
title: "Lighbox Tests"
author: Nick Strayer
date: '2019-10-29'
excerpt: "Hopefully this works!"
---

```{r, include = FALSE}
lightboxed_margin <- function(content){
  wrapped_content <- paste("<span class = 'lightbox'>", content, "</span>")
  tufte::margin_note(wrapped_content)
}
```

## Hi!

Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. 

`r lightboxed_margin("![](link_to_chest_photo.png) Here's a tricky-to-size image.")`

It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.



````

**Comment by howardm** [comment]
It's great!  Thanks.

Two things:

1. I had to put the lightbox js code at the top of my .Rmd. The static folder (Master) in Tuftesque theme does not contain a js folder. 

2. A radiologist would really like a completely black background around the lightboxed image  :-)
 
That is, this:

___

![Screen Shot 2019-10-29 at 8 55 23 PM](https://user-images.githubusercontent.com/6101226/67825517-26d0db80-fa8f-11e9-8500-e33171b32c10.jpg)

___

Rather than this:

___

![Screen Shot 2019-10-29 at 8 54 13 PM](https://user-images.githubusercontent.com/6101226/67825545-423be680-fa8f-11e9-922e-611bcf30760c.jpg)

_____

I presume I can modify the lightbox.css for this (personal) purpose. How do I do so ?

Much obliged,

Howard

**Comment by nstrayer** [comment]
Okay! 

So for some reason I got confused and forgot I had a lightbox branch. Updated the master to _actually_ have all the needed files now so so need to use the js or css chunks. 

I agree that a lightbox should probably make the background less present. I updated the CSS so now the lightboxes (almost) entirely block out the background. 

![image](https://user-images.githubusercontent.com/6764693/67872417-e78ea300-faff-11e9-8654-5da0ad89466b.png)

I did keep a tiny bit of transparency in the background so the user doesn't think they got navigated to another page. That being said, if desired, you can make it entirely black by overriding with a custom css chunk: 

````
```{css, echo = FALSE}
.lightbox-loaded {
  box-shadow: 0 0 6px 50vw black !important;
}
```
````

I also added two little extras that don't pertain necessarily to the issues at hand but now when mousing over a lightbox-able image, the cursor will change to a zoom-in icon and when the lightbox is active the cursor will change to a zoom-out icon. Also, a small tooltip will popup letting the user know that if they click it will expand the image.

**Comment by howardm** [comment]
Great!

Everything works very nicely, except for one thing:

I still have to put the lightbox .js code itself into the .Rmd file. If I don't, the lightbox function doesn't work for me. I do have the js folder in the `static` folder containing the `lightbox.js` file within.

Do I have to reference the lightbox function somewhere in the .Rmd file or the header ?

Maybe I messed up somewhere along the line.

Howard

**Comment by nstrayer** [comment]
Funky. You shouldn't have to. 

When you look at `themes/tuftesque/layouts/partials/header.includes.html` does line 29 import`js/lightbox.js`? See [here](https://github.com/nstrayer/tuftesque/blob/master/layouts/partials/header.includes.html#L29) for what it should be.

**Comment by howardm** [comment]
Ah, I previously placed an edited version of that file (header.includes.html) in a layouts folder in the root of my website.

I added the line to it, and all is now well.

Thanks!

Howard

**Comment by nstrayer** [comment]
Wonderful! Let me know if anything acts up again!
