### ISSUE TITLE
footer fix from mmrath/hugo-bootstrap@33dba4c

### ISSUE THREAD

**Issue by chrishandyblog** [nstrayer/tuftesque#3]
change line 21 to +      &copy; {{now.Format "2006"}}

**Comment by chrishandyblog** [comment]
New to Github issues and stuff. probably not doing this right. and found a fix for errors in themes/tuftesque/layouts/partials/footer.html when building based on your theme. Thanks!

Found it here: https://github.com/mmrath/hugo-bootstrap/commit/33dba4c20f1111399f495f2533c465c4402a6208

**Comment by nstrayer** [comment]
Fixed https://github.com/nstrayer/tuftesque/pull/9 Thanks!
