### ISSUE TITLE
ERROR and WARNING with Hugo v0.26

### ISSUE THREAD

**Issue by nancym** [nstrayer/tuftesque#6]
I'm using Hugo v0.26 and just tried to build the exampleSite. It said this:

```
Started building sites ...
ERROR 2017/08/14 15:41:38 Page's Now is deprecated and will be removed in Hugo 0.27. Use now (the template func).
WARNING: calling IsSet with unsupported type "invalid" (<nil>) will always return false.
```
Thanks for this theme!

**Comment by igutierrezm** [comment]
I had the same problem. In ~\themes\tuftesque\layouts\partials\footer.html
replace line 21 with
      &copy; {{now.Format "2006"}}
(It worked for me, but I do not know if it is the best solution)

**Comment by nstrayer** [comment]
Ah, I get this too and have managed to ignore it until now. I'll look into this. Thanks!

**Comment by nstrayer** [comment]
I believe I fixed this using exactly your solution @igutierrezm. See https://github.com/nstrayer/tuftesque/pull/9
